### PR TITLE
Text Replacements and UTF-8 Presets Implementation.

### PR DESCRIPTION
**Pull request by AwesomestCode**
Implements issue #112 

*This is a draft*

### CODE REVIEW

**Comment by AwesomestCode** [comment]
This is a draft currently. It is not 100% finished as configurable replacements are not implemented.

**Comment by AwesomestCode** [comment]
Functionality is all added.

**Comment by BrainStone** [comment]
This is good for merging (I'll fix a few teeny tiny things myself, don't worry).

**Comment by BrainStone** [comment]
Will be merged into it's own branch until there's a decent list of defaults

**Pull request merged**
