### PR TITLE
Global message executed by symbol is no longer passed to the local Chat

### PR DESCRIPTION
**Pull request by Peda1996**

### CODE REVIEW

**Comment by Peda1996** [comment]
see https://github.com/AuraDevelopmentTeam/BungeeChat2/issues/181

**Comment by BrainStone** [comment]
Please format the code according to the repository standard by running `./gradlew spotlessApply`.

**Comment by Peda1996** [comment]
Yes you are correct :)
Bdw. I changed the formatting ;)

**Comment by BrainStone** [comment]
Now I can actually see what you changed.

Makes a lot of sense. Thanks for the contribution :D

**Pull request merged**
