### PR TITLE
Add zh_CN  translation of plugin messages

### PR DESCRIPTION
**Pull request by povsister**
Very nice plugin just perfectly solved the chatting problem on my cluster MC servers.

This PR only contains zh_CN translation, causing I am not familiar with zh_TW.

Anybody else living in HK or TW, pls feel free to convert this to traditional Chinese.
Or you can just translate your own, whatever.

### CODE REVIEW

**Comment by BrainStone** [comment]
Thank you for the pull request.

The build failure is due to my servers currently being down and me trying to recover them.
That's also the reason I'll hold this PR.
Once everything is settled I'll be happy to merge it.

**Comment by BrainStone** [comment]
Since everything looks good, I'll be happy to merge it.

I'm not a language expert and not at all familar with the different varieties of Chinese but would it make sense to have zh_TW inherit from zh_CN?  
That means that if in zh_TW a language key is missing the one in zh_CN will be used.

**Comment by povsister** [comment]
I strongly suggest NOT doing so.
Traditional Chinese really differs a lot from Simplified Chinese in some aspects.

To be frank with you, as a native Chinese speaker, I usually encounter problems recognizing the character written in traditional Chinese, let alone understanding their means.
It's pretty common in our generation. I have some friends living in Taiwan are also complaining to me of simplified Chinese when they make online purchase from China mainland.

**Comment by BrainStone** [comment]
No no. I meant that traditional inherits from/falls back to simplified.

**Comment by povsister** [comment]
I understand that you mean make CHS "a backup" of CHT. But it makes little sense.

Typically, there are three forms of written Chinese: Simplified, Traditional and Classical(or known as ancient Chinese). Each of them has its own syntax and vocabulary, A same word may have totally different meaning in different culture . So you can basically treat them as three different languages.
To avoid misleading and confusion, I still suggest using English as a fallback option.

**Comment by BrainStone** [comment]
That makes perfect sense. Thank you for the little language lesson.  
With European languages it's typically the other way round. Like if you take German(Germany) de_DE and German(Switzerland) de_CH, falling back to de_DE in a de_CH file makes sense because while there are differences pretty much all Swiss speakers know the base German language well enough that they can understand with ease. Like if you have the same prefix you typically can fall back to the main version/dialect of the language and it is still easily understandable for all European languages I am aware of.

So thank you again for clearing that up and thank you a lot for translating!

**Comment by povsister** [comment]
haha. Hope someone could do the translation one day.

You get the point. The relationship between different written Chinese is not that simple like super-set/sub-set. Generally it's three types of culture influencing each other.

Let's take the translation of a famous Blizzard game for example.
> English: Overwatch
> CHS: 守望先锋 (means being a pioneer of powerful guardian. which reflects the background of this game)
> CHT: 鬥陣特攻 (from my opinion, it may means special assault on battlefield.. wtf?)

Not only every single word differs. but also the whole meaning.
In fact, my friend in TW told me that the translation is very cool and sounds awesome.
See ?  CULTURE GAP..

**Comment by BrainStone** [comment]
Makes perfect sense. Thank you

**Pull request merged**
