### PR TITLE
Fix ignore system + typo

### PR DESCRIPTION
**Pull request by CryLegend**

### CODE REVIEW

**Comment by BrainStone** [comment]
Thank you for the contribution.

**Comment by BrainStone** [comment]
@CryLegend What name should I put in the contributors list?

**Comment by CryLegend** [comment]
@BrainStone Minor pull request. No need to.

**Comment by BrainStone** [comment]
You're in already :P 
So what should I put?

**Comment by CryLegend** [comment]
Oh :p CryLegend is fine don't worry. Thanks.

**Comment by BrainStone** [comment]
Alright. Thank you. I've had several complaints that the ignore system wasn't working but could never figure out why it wasn't working xD

**Comment by CryLegend** [comment]
My admins spammed me to solve this problem since 1 month lol

**Pull request merged**
