### PR TITLE
Add permission to block usage of chat 

### LINKED ISSUE #86: Add permission to block usage of chat
#### Issue Description: 
I have a role visitor. for someone who did'nt make candidate. (so don't accept the rules)
So this person can not build and talk with other

So, it will be cool to have a permission to
allow ou deny (as you want) in the localchat

Thanks

PS: I currently on latest dev version

### PR DESCRIPTION
**Pull request by jewome62**
Add permission to localchat
if not else permission, the message is not send

Fix #86

### CODE REVIEW

**Comment by BrainStone** [comment]
You did not add the permissions that were requested in #86

**Comment by jewome62** [comment]
I fix the permission name
for ci, this is not relevant about this PR
```
6
Expected feature release number in range of 9 to 14, but got: 8
167
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
```

**Comment by jewome62** [comment]
@BrainStone Did you have news ?

**Comment by BrainStone** [comment]
The issue I have with this PR, that it only cares for one type of chat.

I haven't thought about throughly, but will give you an update soon. Please don't change anything for now.

**Comment by BrainStone** [comment]
Alright.  
So this has come up again and I spent some time thinking about how I would like to have it.

We essentially have 3 channels
local, global and staffchat
Running either command on it's own should send you to to that channel
If they are already there send them to the default.

So a new local command would be added.

Is that something you'd like implement? (In this PR or a new one)

**Comment by jewome62** [comment]
Fixed by new command /local
https://github.com/AuraDevelopmentTeam/BungeeChat2/commit/93e14f870aa7b12d8bfb6edaaff24cf69673da52

**Pull request closed without merging**
