### PR TITLE
Broadcast mute message and save to mute state

### PR DESCRIPTION
**Pull request by PonyPC**

### CODE REVIEW

**Comment by BrainStone** [comment]
Why do you save the changes right away? The user will be saved when they leave.
Also it's not broadcasting intentionally.

**Comment by PonyPC** [comment]
Because I use mysql as backend , sometime it lost mute state after bungeecord stop.

**Comment by BrainStone** [comment]
> sometime it lost mute state after bungeecord stop.

Well that is something I can look into.
But I certainly won't accept a band aid fix that won't even cover 10% of the plugin.

**Comment by PonyPC** [comment]
Never mind, I just don't want to build by myself. Btw, download link is dead again.

**Comment by BrainStone** [comment]
Which download link?

**Comment by PonyPC** [comment]
Releases: https://maven.aura-dev.team/repository/auradev-releases/
Snapshots: https://maven.aura-dev.team/repository/auradev-snapshots/
both of them 20 minutes ago. But it seems that working now.

**Comment by BrainStone** [comment]
Strange. But good to know that it's working now.

**Pull request closed without merging**
